# Load joint trajectory controller
controller_list:
  - name: r_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
  - name: l_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint

  - name: r_gripper_controller
    action_ns: gripper_action
    type: GripperCommand     
    default: true
    joint:
    - r_gripper_joint
    - r_gripper_palm_joint
    - r_gripper_l_finger_joint
    - r_gripper_l_finger_tip_joint
    - r_gripper_r_finger_joint
    - r_gripper_r_finger_tip_joint
   
  - name: l_gripper_controller
    action_ns: gripper_action
    type: GripperCommand     
    default: true
    joints:
    - l_gripper_joint
    - l_gripper_palm_joint
    - l_gripper_l_finger_joint
    - l_gripper_l_finger_tip_joint
    - l_gripper_r_finger_joint
    - l_gripper_r_finger_tip_joint
   
